[package]
name = "yunhai-bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "Yunhai"
crate-type = ["cdylib"]

[dependencies]
imagesize = "0.13"
sysinfo = { path = "../sysinfo" }
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true
